const content = {
  en: {
    RegistrationButton: "Sign up",
    SignInButton: "Sign in",
    SignUp: "Sign up",
    SignIn: "Sign in",
    LogOut: "Log out",
    EditProfileEditForm: "Edit Profile",
    NameEditForm: "Name",
    AboutEditForm: "About",
    NewPlaceNewCardForm: "New Place",
    NewPlaceCaption: "Caption",
    NewLink: "Picture Link",
    SignUpButton: "Sign Up",
    SaveButton: "Save",
    SavingButton: "Saving ...",
    EditAvatar: "Edit avatar",
    Password: "Password",
    LoginError: "Something went wrong! Please try again!",
    SuccessSignUp: "You have registered successfully!",
    AlreadySignedUpCaption: "Already signed up?",
  },
  ru: {
    RegistrationButton: "Регистрация",
    SignInButton: "Войти",
    SignUp: "Регистрация",
    SignIn: "Вход",
    LogOut: "Выход",
    EditProfileEditForm: "Редактировать профиль",
    NameEditForm: "Имя",
    AboutEditForm: "О себе",
    NewPlaceNewCardForm: "Новое место",
    NewPlaceCaption: "Описание",
    NewLink: "Ссылка на картинку",
    SignUpButton: "Зарегистрироваться",
    SaveButton: "Сохранить",
    SavingButton: "Сохранеие ...",
    EditAvatar: "Обновить аватар",
    Password: "Пароль",
    LoginError: "Что-то пошло не так! Попробуйте ещё раз!",
    SuccessSignUp: "Вы успешно зарегистрировались!",
    AlreadySignedUpCaption: "Уже зарегистрированы?",
  },
};

module.exports = { content };
